### PR TITLE
Use text-based track storage format.

### PR DESCRIPTION
**Pull request by rdoeffinger**
Maybe not very Java-style, but much easier to process
in other applications, to debug and more robust -
e.g. no issues when renaming the classes.
Also a lot smaller for typical marker file sizes.
Potentially more maintenance effort though if the
structure changes significantly in the future.

Signed-off-by: Reimar Döffinger Reimar.Doeffinger@gmx.de

### CODE REVIEW

**Comment by diedricm** [comment]
I do not really like text based formats when their actual content is not meant to be changed by users. I'll try to build a more object oriented binary serialization that wont break the way java serialization does the next few days. If I fail doing that, then I'll merge this here.

**Comment by rdoeffinger** [comment]
I have to admit, my thinking is rather the other way round: I'd only use a binary format if using text is too much of a pain.
In this case the data contained is simple enough that it being viewable and editable in my opinion is a plus. It also has the advantage that supporting leaving out the "time" fields for example (which seem fairly pointless) is easy to do and detect, binary formats are usually more likely to need to bump the revision number and thus need extra code for forward/backward compatibility.
And as said, the debug part. If I had been able to actually read the track files it might have saved me a few hours debugging (admittedly because debugging on Android at least for a newcomer is a huge pain).
Not that I particularly mind a binary format, but at least not having any Java-specifics and being able to understand it with the help of a hex editor would be nice...
Otherwise I'd be back to having to think about adding an "export" feature for something that can interoperate with non-Java-based programs (no concrete plans yet, but I might want a desktop  and/or web based viewer/editor at some point. And I really, really, don't want anything Java based for that).

**Comment by diedricm** [comment]
Using LDMIOTrack.printValuesAsCSV() you can debug the points using tools as http://www.gpsvisualizer.com/ . It might be useful to you to add the CSV's as another ILDMIO implementation.

I’m also all for abandoning the Java serialization. I'll just try out if I can build something useful.

**Comment by diedricm** [comment]
Okay so I still don’t like this very much, but I also don’t want to delay you releasing MapEver much more. I thought I would have time the last days, but my protobuf solution and TrackDB replacement still isn’t ready yet.

I will have more time for this after next Monday.

**Comment by rdoeffinger** [comment]
I actually put up an "alpha" version for testing up already. It has a grand total of 2 extra users besides me, so no harm done I'd say. I kept the old format though.
If you plan to change it anyway I am not sure we should make a release with this, it's too many variants to support.
I have to admit I am not a great fan of protobuf personally, it is an extra dependency and for such simple data badly bloated/overkill. Especially if your main issue is the text format, because that could be solved by just using a DataOutputStream/DataInputStream to write the data directly...

**Pull request merged**
