### PR TITLE
Add new experimental locator.

### PR DESCRIPTION
**Pull request by rdoeffinger**
Uses a least-squares linear solver.
Weighing to be added, plus general fine-tuning,
optimization, code-cleanup...

Signed-off-by: Reimar Döffinger Reimar.Doeffinger@gmx.de

### CODE REVIEW

**Comment by diedricm** [comment]
What do you intend to use `private Marker findMarkerByPoint()` for? This function was actually used to parse the data that came out of opencv.

**Comment by rdoeffinger** [comment]
That was a brainfart, for some reason I thought it was a public interface function I'd need.
Removed.

**Comment by diedricm** [comment]
Okay tested using testloc.world. It somehow returns a constant value for me. It always returns x=1100,y=638

**Comment by rdoeffinger** [comment]
I couldn't test with testloc so far, besides that I couldn't figure out how to use it earlier, jogl is now an issue. The only jogl version it works with seems to be the one included in its dowload zip.
With that fixed I still have no clue how to use it though.
Clicking on "new file" works in principle, but doesn't even create an empty track file and doesn't display the image either.
Clicking on the "Mode: Move" button for some reason activates the two buttons to the left of it, but doesn't actually change the mode. (Why does the button do something even though it is greyed out??)
It does work with the Android app (or rather: it worked yesterday after some compile fixes, have not tried since), so one possible issue is that it does not make a deep copy of the marker list, so if testloc modifies that at any point before doing queries it won't get any results for example.

**Comment by rdoeffinger** [comment]
I also get quite a few null pointer exceptions, even though I am not actually able to do anything really:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at de.hu_berlin.informatik.spws2014.testloc_world.testloc_world$TestlocWorldFrame.resetToIndex(testloc_world.java:187)
        at de.hu_berlin.informatik.spws2014.testloc_world.testloc_world$TestlocWorldFrame.access$000(testloc_world.java:75)
        at de.hu_berlin.informatik.spws2014.testloc_world.testloc_world$TestlocWorldFrame$3.mouseClicked(testloc_world.java:386)
        at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)

**Comment by rdoeffinger** [comment]
If I copy the data from my phone, it does not display any existing tracks. However it at least displays the image after "new file", it possibly needed a track.conf?
Either way, it works now.
And it works correctly, for me as soon as you have at least 3 markers.
With less than that it seems to display random stuff instead of noticing the error or something like that?

**Comment by rdoeffinger** [comment]
Also setting markers on the right side of a full resolution camera image fails with "Point greater than image size!".

**Comment by diedricm** [comment]
For running testloc you should download the worldwind sdk and copy the jogl and whatnot files needed for your platform somewhere where java can find them. I have "gluegen-rt-natives-linux-amd64.jar" and "jogl-all-natives-linux-amd64.jar" in the same dir as jogl-all.jar and it works.

The track file is only created after clicking save file ... it could be done automatic, but I mostly developed it for my own use, so its kinda rough around the edges.

If a greyed out button works than that’s strange, I'm calling setEnabled(false) on them. If this continues to happen for you than please describe that in another issue further.

The markers committed through newMarkerAdded will never be changed, however the list they are passed in may. Maybe this should be more clear ... also the name for this function is very misleading hmm ... gonna change that.

Did you move the slider? The slider represents your time in the track file. Loading a map always sets the time to 0, meaning that the simulator thinks that no position arrived yet. So simply try to move the slider.

No track.conf is not used in testloc.

"Point greater than image size!"
Yeah I already fixed that one some time ago in the private git ... wait a moment.

**Comment by rdoeffinger** [comment]
Well, not sure why it didn't work originally, might be user error.
Anyway I kind of could reproduce your issue (with the Android emulator I used too simple GPS coordinates) and pushed a fix for it.

**Comment by rdoeffinger** [comment]
I don't know if you want to separate it out, but I found why I got strange results with only 2 markers.
getOrthogonal rotated the GPS coordinates opposite to the map coordinates, thus the resulting mapping was mirrored.

**Comment by diedricm** [comment]
about getOrthogonal: I think that is depended on how the map is rotated relative to the lat/lon plane, as you have to guess the sign and factor of the orthogonal vector. We can change it however, as we're only guessing there it doesn’t matter.

Cool it works now. Have only tested it with one track where there are only 3 markers. Will do tests with the more interesting cases with 4+ markers tomorrow. Maybe I should create a repo for these tests.

Couldn’t you also do most of getPointPosition in newMarkerAdded as most is independent from currentPosition? Not that the computation is expensive, but it just doesn’t really seem correct there.

Other than that I would merge, but it seems to me that you still want to do stuff where all the TODOs are. Tell me when you think its ready.

**Comment by rdoeffinger** [comment]
> I think that is depended on how the map is rotated relative to the lat/lon plane

No, a clockwise rotation stays a clockwise rotation no matter how you rotate (and the right side of a directed line as we have here stays the right side independent of rotation).
Kind of the only thing that can break it is if you mirror along a line, in which case it swaps.
I was confused a bit about the GPS coordinate system, but I think that is not an issue. Unfortunately different scales along x and y are though and cause significant errors here (and I think getting worse further north - and I suspect all MapEver algorithms would break down around the north pole), and as I am sure there is a formula for that it would be nice to apply it.

> Couldn’t you also do most of getPointPosition in newMarkerAdded as most is independent from currentPosition?

That is related to the weight TODOs and no longer the case in the latest version.

> Other than that I would merge, but it seems to me that you still want to do stuff where all the TODOs are. 

I think it is good enough for the moment, though I definitely will have to do real-world testing the next weekend with good weather.
The next steps would be making it configurable on the app side, but for that it would be good to have the submodule contain it.
I'll also have to check if I can do something about crashes when I use a full-resolution camera image and zoom in, is that a known thing? (just in case you know)

**Comment by diedricm** [comment]
> and I suspect all MapEver algorithms would break down around the north pole

It will also break horribly if you dare to go from + to - or other way around ...

I put your scaling issue in the other repo, as it is with the android app.

**Comment by rdoeffinger** [comment]
> It will also break horribly if you dare to go from + to - or other way around ...

If you mean at the equator or Greenwich, I don't think so. Only the 180 meridian I'd expect to be an issue.
The likelihood that someone from Fiji or the Siberian east cost will ever complain seems fairly low though (and I expect we will have major issues even with more than 2 points there...)

**Pull request merged**
